/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliaria_empesa;

import Atxy2k.CustomTextField.RestrictedTextField;
import clases_usuarios.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro y Marta
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar2
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellido1TextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellido2TextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefonoTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MailField = new javax.swing.JTextField();
        registrarYSalirBotton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        edadtextfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nickTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ContrasenajTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_empresa/96.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hazte socio");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nombreTextField1.setBackground(new java.awt.Color(255, 255, 255));
        nombreTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextField1ActionPerformed(evt);
            }
        });
        nombreTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTextField1KeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Primer Apellido");

        apellido1TextField2.setBackground(new java.awt.Color(255, 255, 255));
        apellido1TextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellido1TextField2KeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Segundo apellido");

        apellido2TextField3.setBackground(new java.awt.Color(255, 255, 255));
        apellido2TextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellido2TextField3KeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numero de telefono");

        telefonoTextField4.setBackground(new java.awt.Color(255, 255, 255));
        telefonoTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextField4ActionPerformed(evt);
            }
        });
        telefonoTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTextField4KeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mail");

        MailField.setBackground(new java.awt.Color(255, 255, 255));
        MailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailFieldActionPerformed(evt);
            }
        });

        registrarYSalirBotton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registrarYSalirBotton.setText("Registrar y salir");
        registrarYSalirBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarYSalirBottonActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Edad");

        edadtextfield.setBackground(new java.awt.Color(255, 255, 255));
        edadtextfield.setForeground(new java.awt.Color(0, 0, 0));
        edadtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadtextfieldActionPerformed(evt);
            }
        });
        edadtextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadtextfieldKeyTyped(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Apodo");

        nickTextField.setBackground(new java.awt.Color(255, 255, 255));
        nickTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");

        ContrasenajTextField1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(telefonoTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(apellido2TextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido1TextField2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 380, Short.MAX_VALUE)
                        .addComponent(registrarYSalirBotton)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nickTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(MailField)
                    .addComponent(jLabel9)
                    .addComponent(edadtextfield)
                    .addComponent(ContrasenajTextField1)
                    .addComponent(jLabel7))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellido1TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellido2TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edadtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContrasenajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarYSalirBotton)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nickTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickTextFieldActionPerformed

    private void edadtextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadtextfieldKeyTyped
        // TODO add your handling code here:
        RestrictedTextField r= new RestrictedTextField(edadtextfield);
        r.setLimit(4);
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane,"Ingresar solo números");
        }
    }//GEN-LAST:event_edadtextfieldKeyTyped

    private void edadtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadtextfieldActionPerformed

    private void telefonoTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTextField4KeyTyped
        // TODO add your handling code here:
        RestrictedTextField r= new RestrictedTextField(telefonoTextField4);
        r.setLimit(20);
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane,"Ingresar solo números");
        }
    }//GEN-LAST:event_telefonoTextField4KeyTyped

    private void telefonoTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextField4ActionPerformed

    private void apellido2TextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellido2TextField3KeyTyped
        // TODO add your handling code here:
        RestrictedTextField r= new RestrictedTextField(apellido2TextField3);
        r.setLimit(30);
        char validad=evt.getKeyChar();

        if(Character.isDigit(validad)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane,"Ingresar solo letras");
        }
    }//GEN-LAST:event_apellido2TextField3KeyTyped

    private void apellido1TextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellido1TextField2KeyTyped
        // TODO add your handling code here:
        RestrictedTextField r= new RestrictedTextField(apellido1TextField2);
        r.setLimit(30);
        char validad=evt.getKeyChar();

        if(Character.isDigit(validad)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane,"Ingresar solo letras");
        }
    }//GEN-LAST:event_apellido1TextField2KeyTyped

    private void nombreTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextField1KeyTyped
        // TODO add your handling code here:
        RestrictedTextField r= new RestrictedTextField(nombreTextField1);
        r.setLimit(30);
        char validad=evt.getKeyChar();

        if(Character.isDigit(validad)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane,"Ingresar solo letras");
        }
    }//GEN-LAST:event_nombreTextField1KeyTyped

    private void nombreTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextField1ActionPerformed

    private void registrarYSalirBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarYSalirBottonActionPerformed
        // TODO add your handling code here:
        
        Usuario usu=new Usuario();
        Usuario meter=new Usuario();
        //creamos variables donde entraran los datos de la interfez grafica
        String nombre=nombreTextField1.getText();
        String nick=nickTextField.getText();
        String contrasena=ContrasenajTextField1.getText();
        int edad=Integer.parseInt(edadtextfield.getText());
        String apellido1=apellido1TextField2.getText();
        String apellido2=apellido2TextField3.getText();
        String correo=MailField.getText();
        String num_telefono=telefonoTextField4.getText();
        //aqui metemos los datos para el metodo
        usu.setNombre(nombre);
        usu.setApellido1(apellido1);
        usu.setApellido2(apellido2);
        usu.setCorreo(correo);
        usu.setContrasena(contrasena);
        usu.setNumero_telefono(num_telefono);
        usu.setNick(nick);
        usu.setFecha_nacimiento(edad);
        try {
            meter.agregarUsuario(usu);
            JOptionPane.showMessageDialog(null,"Te has hecho socio");
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Ha fallado");
        }
        
        
    }//GEN-LAST:event_registrarYSalirBottonActionPerformed

    private void MailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContrasenajTextField1;
    private javax.swing.JTextField MailField;
    private javax.swing.JTextField apellido1TextField2;
    private javax.swing.JTextField apellido2TextField3;
    private javax.swing.JTextField edadtextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nickTextField;
    private javax.swing.JTextField nombreTextField1;
    private javax.swing.JButton registrarYSalirBotton;
    private javax.swing.JTextField telefonoTextField4;
    // End of variables declaration//GEN-END:variables
}
